"""The pools patient and practitioner names are drawn from, in allocation order.

Two ordered tuples, walked in order, so the same creation sequence in a fresh session
always produces the same names. Order is therefore part of the contract: appending is
safe, reordering is not.

Every name belongs to a widely recognized figure who died more than fifty years ago -
long enough that no living person is being named, and recognizable enough that a demo
reads as deliberate rather than as scraped data.
"""

# 100 writers, for patients.
WRITER_POOL: tuple[str, ...] = (
    "Jane Austen",
    "Charles Dickens",
    "Leo Tolstoy",
    "Fyodor Dostoevsky",
    "Mark Twain",
    "Emily Dickinson",
    "Victor Hugo",
    "Gustave Flaubert",
    "Herman Melville",
    "Walt Whitman",
    "Oscar Wilde",
    "Anton Chekhov",
    "Joseph Conrad",
    "Franz Kafka",
    "Marcel Proust",
    "Virginia Woolf",
    "James Joyce",
    "George Orwell",
    "Rabindranath Tagore",
    "Natsume Soseki",
    "Lu Xun",
    "Emile Zola",
    "Henrik Ibsen",
    "August Strindberg",
    "Selma Lagerlof",
    "Knut Hamsun",
    "Thomas Mann",
    "Hermann Hesse",
    "Bertolt Brecht",
    "Robert Musil",
    "Stefan Zweig",
    "Rainer Maria Rilke",
    "Federico Garcia Lorca",
    "Miguel de Unamuno",
    "Antonio Machado",
    "Fernando Pessoa",
    "Luigi Pirandello",
    "Italo Svevo",
    "Giovanni Verga",
    "Anatole France",
    "Andre Gide",
    "Paul Valery",
    "Guillaume Apollinaire",
    "Romain Rolland",
    "Maxim Gorky",
    "Ivan Turgenev",
    "Nikolai Gogol",
    "Alexander Pushkin",
    "Mikhail Lermontov",
    "Boris Pasternak",
    "Anna Akhmatova",
    "Osip Mandelstam",
    "Marina Tsvetaeva",
    "Mikhail Bulgakov",
    "Isaac Babel",
    "Yevgeny Zamyatin",
    "Edith Wharton",
    "Willa Cather",
    "Sinclair Lewis",
    "Sherwood Anderson",
    "Theodore Dreiser",
    "Gertrude Stein",
    "Eugene O'Neill",
    "Ernest Hemingway",
    "William Faulkner",
    "John Steinbeck",
    "Langston Hughes",
    "Zora Neale Hurston",
    "Flannery O'Connor",
    "Carson McCullers",
    "Jack Kerouac",
    "Edward Morgan Forster",
    "Aldous Huxley",
    "Clive Staples Lewis",
    "Sylvia Plath",
    "Dorothy Parker",
    "Upton Sinclair",
    "Erich Maria Remarque",
    "John Dos Passos",
    "Yukio Mishima",
    "Yasunari Kawabata",
    "Pablo Neruda",
    "Wystan Hugh Auden",
    "Par Lagerkvist",
    "Mary Shelley",
    "Charlotte Bronte",
    "Emily Bronte",
    "Anne Bronte",
    "George Eliot",
    "Elizabeth Gaskell",
    "Thomas Hardy",
    "Rudyard Kipling",
    "Arthur Conan Doyle",
    "Robert Louis Stevenson",
    "Lewis Carroll",
    "Bram Stoker",
    "Jules Verne",
    "Alexandre Dumas",
    "Honore de Balzac",
    "Guy de Maupassant",
)

# 20 physicians, for practitioners.
PHYSICIAN_POOL: tuple[str, ...] = (
    "William Osler",
    "Andreas Vesalius",
    "William Harvey",
    "Edward Jenner",
    "Rene Laennec",
    "Ignaz Semmelweis",
    "Rudolf Virchow",
    "Joseph Lister",
    "Robert Koch",
    "Paul Ehrlich",
    "Santiago Ramon y Cajal",
    "Ivan Pavlov",
    "Frederick Banting",
    "Alexander Fleming",
    "Howard Florey",
    "Elizabeth Blackwell",
    "Karl Landsteiner",
    "Harvey Cushing",
    "Alois Alzheimer",
    "Jean-Martin Charcot",
)
