# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scheduling_pb2 as scheduling_dot_v1_dot_scheduling__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scheduling/v1/scheduling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulingStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsureSessionProvisioned = channel.unary_unary(
                '/scheduling.v1.Scheduling/EnsureSessionProvisioned',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedResponse.FromString,
                _registered_method=True)
        self.RenamePatient = channel.unary_unary(
                '/scheduling.v1.Scheduling/RenamePatient',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.RenamePatientRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.RenamePatientResponse.FromString,
                _registered_method=True)
        self.ListPractitioners = channel.unary_unary(
                '/scheduling.v1.Scheduling/ListPractitioners',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/scheduling.v1.Scheduling/CheckAvailability',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.BookAppointment = channel.unary_unary(
                '/scheduling.v1.Scheduling/BookAppointment',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentResponse.FromString,
                _registered_method=True)
        self.RescheduleAppointment = channel.unary_unary(
                '/scheduling.v1.Scheduling/RescheduleAppointment',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.RescheduleAppointmentRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.FromString,
                _registered_method=True)
        self.CancelAppointment = channel.unary_unary(
                '/scheduling.v1.Scheduling/CancelAppointment',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.CancelAppointmentRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.FromString,
                _registered_method=True)
        self.ListAppointments = channel.unary_unary(
                '/scheduling.v1.Scheduling/ListAppointments',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsResponse.FromString,
                _registered_method=True)
        self.DeletePatientForChat = channel.unary_unary(
                '/scheduling.v1.Scheduling/DeletePatientForChat',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/scheduling.v1.Scheduling/DeleteSession',
                request_serializer=scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)


class SchedulingServicer:
    """Missing associated documentation comment in .proto file."""

    def EnsureSessionProvisioned(self, request, context):
        """Idempotent per-session provisioning: creates this chat's patient if absent, and one
        default practitioner if the session has none. Safe to call on every visit (FR-042, FR-045).
        NOT_FOUND when `chat_id` already belongs to a patient of another session: the chat is unique
        across the whole store, so a mismatched one is never answered with that patient.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenamePatient(self, request, context):
        """Rename one patient. Idempotent: renaming to the name it already has succeeds and
        changes nothing, so a caller whose deadline expired may safely retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPractitioners(self, request, context):
        """Every practitioner in the session, with specialty and schedule (FR-030).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Bookable start times for one practitioner over a window (FR-024).
        NOT_FOUND when the practitioner or the patient does not resolve in this session:
        this response has no typed-failure channel, and an empty result already means
        something else entirely (see CheckAvailabilityResponse.truncated). The status
        DETAIL carries which one failed, as a `shared_models.NotFoundEntity` value —
        NOT_FOUND has no typed payload, so the detail string is that part of the contract.
        INVALID_ARGUMENT when `to_date` precedes `from_date`, which would otherwise walk
        zero days and answer with that same "nothing bookable" shape.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookAppointment(self, request, context):
        """Create one appointment, or explain why it was refused (FR-016..FR-021, FR-051).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RescheduleAppointment(self, request, context):
        """Move an appointment: a new start, and optionally a new practitioner, applied together as
        one write (006 FR-001..FR-003). The appointment keeps its identifier and its patient.

        Carries NO idempotency key, deliberately (006 FR-020): the request asserts the state the
        appointment is to end in, so re-sending it cannot bring a second appointment into being. A
        key derived from that target state would be worse than none — states recur, and
        09:00 -> 10:00 -> 09:00 -> 10:00 would derive the first move's key on the third and replay
        it, leaving the appointment at 09:00 while reporting success.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAppointment(self, request, context):
        """Cancel an appointment. The record is retained and marked cancelled (006 FR-009): it keeps
        its identifier, its practitioner and its times, stops occupying its slot (006 FR-010), and
        releases the idempotency key that created it (006 FR-011).

        Cancelling an already-cancelled appointment returns `no_change`, NOT a failure — the
        appointment is in the state that was asked for (006 FR-017, FR-019). This is
        distinguishable from an appointment that never existed, which is
        `failure(APPOINTMENT_NOT_FOUND)`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAppointments(self, request, context):
        """This patient's appointments: two independent axes in, two separately bounded legs out
        (006 FR-013..FR-016). Replaces `ListUpcomingAppointments`, whose FUTURE + STANDING corner
        is exactly what it returned.

        NOT_FOUND (detail: `NotFoundEntity.PATIENT`) when the patient does not resolve in this
        session — two empty legs mean the patient exists and has nothing matching, and one value
        must not stand for both.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePatientForChat(self, request, context):
        """Hard-delete this chat's patient and, by cascade, that patient's appointments (FR-039).
        Idempotent: deleting an already-absent patient succeeds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Hard-delete everything this session owns here: its practitioners, its patients, and - by the
        FK cascades 005 created - their appointments (007 FR-047). Those cascades are deliberately
        status-blind, so CANCELLED appointments go with the rest: a cancelled appointment is still
        that session's row.

        One transaction, so the caller's per-session report has two outcomes to distinguish rather
        than a spectrum. Idempotent, and that is load-bearing rather than incidental: re-running a
        deletion reported incomplete must be safe and must converge. Deleting a session that owns
        nothing - including one that never existed - succeeds with every count at zero, and is NOT
        NOT_FOUND: "already gone" and "was never here" are the same end state here.

        No idempotency key: this creates nothing, so a re-send cannot duplicate anything.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsureSessionProvisioned': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureSessionProvisioned,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedResponse.SerializeToString,
            ),
            'RenamePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.RenamePatient,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.RenamePatientRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.RenamePatientResponse.SerializeToString,
            ),
            'ListPractitioners': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPractitioners,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'BookAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.BookAppointment,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentResponse.SerializeToString,
            ),
            'RescheduleAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.RescheduleAppointment,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.RescheduleAppointmentRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.SerializeToString,
            ),
            'CancelAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAppointment,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.CancelAppointmentRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.SerializeToString,
            ),
            'ListAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAppointments,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsResponse.SerializeToString,
            ),
            'DeletePatientForChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePatientForChat,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionRequest.FromString,
                    response_serializer=scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduling.v1.Scheduling', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduling.v1.Scheduling', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduling:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnsureSessionProvisioned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/EnsureSessionProvisioned',
            scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.EnsureSessionProvisionedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenamePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/RenamePatient',
            scheduling_dot_v1_dot_scheduling__pb2.RenamePatientRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.RenamePatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPractitioners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/ListPractitioners',
            scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.ListPractitionersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/CheckAvailability',
            scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/BookAppointment',
            scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.BookAppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RescheduleAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/RescheduleAppointment',
            scheduling_dot_v1_dot_scheduling__pb2.RescheduleAppointmentRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/CancelAppointment',
            scheduling_dot_v1_dot_scheduling__pb2.CancelAppointmentRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.ChangeAppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/ListAppointments',
            scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.ListAppointmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePatientForChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/DeletePatientForChat',
            scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.DeletePatientForChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.v1.Scheduling/DeleteSession',
            scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionRequest.SerializeToString,
            scheduling_dot_v1_dot_scheduling__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
