# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduling/v1/scheduling.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scheduling/v1/scheduling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1escheduling/v1/scheduling.proto\x12\rscheduling.v1\"-\n\x18\x43heckAvailabilityRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\"4\n\x19\x43heckAvailabilityResponse\x12\x17\n\x0f\x61vailable_slots\x18\x01 \x03(\t\"M\n\x16\x42ookAppointmentRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x0c\n\x04slot\x18\x03 \x01(\t\"1\n\x17\x42ookAppointmentResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t2\xd6\x01\n\nScheduling\x12\x66\n\x11\x43heckAvailability\x12\'.scheduling.v1.CheckAvailabilityRequest\x1a(.scheduling.v1.CheckAvailabilityResponse\x12`\n\x0f\x42ookAppointment\x12%.scheduling.v1.BookAppointmentRequest\x1a&.scheduling.v1.BookAppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduling.v1.scheduling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_start=49
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_end=94
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_start=96
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_end=148
  _globals['_BOOKAPPOINTMENTREQUEST']._serialized_start=150
  _globals['_BOOKAPPOINTMENTREQUEST']._serialized_end=227
  _globals['_BOOKAPPOINTMENTRESPONSE']._serialized_start=229
  _globals['_BOOKAPPOINTMENTRESPONSE']._serialized_end=278
  _globals['_SCHEDULING']._serialized_start=281
  _globals['_SCHEDULING']._serialized_end=495
# @@protoc_insertion_point(module_scope)
